name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-typecheck:
    # Use self-hosted runner pool with label 'plateshapez'
    runs-on: [self-hosted, plateshapez]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Cache uv and virtualenv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-py3.12-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-py3.12-uv-

      - name: Sync dev dependencies
        shell: bash
        run: |
          uv --version
          uv sync --group dev

      - name: Run formatting, linting, type checks
        shell: bash
        run: |
          chmod +x scripts/check.sh
          ./scripts/check.sh
