name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ${{ github.workspace }}

jobs:
  lint-and-typecheck:
    # Use self-hosted runner pool with label 'plateshapez'
    runs-on: [self-hosted, plateshapez]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          if ! command -v uv >/dev/null 2>&1; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          fi

      - name: Cache uv and virtualenv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-py3.12-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-py3.12-uv-

      - name: Sync dev dependencies
        run: |
          echo "Current dir: $(pwd)"
          test -f pyproject.toml && echo "Found pyproject.toml" || (echo "pyproject.toml missing" && ls -la && exit 1)
          uv --version
          uv sync --group dev

      - name: Run formatting, linting, type checks
        run: |
          chmod +x scripts/check.sh
          ./scripts/check.sh
